### ISSUE TITLE
feat: any refresh on the kea parts?

### ISSUE THREAD

**Issue by sesam** [mariusandra/kea-presentation#1]
Or if there is some "whats new in kea" since then or something?
Also very interested in how importing that `controller.rb` works. Handled via that webpack config?

**Comment by mariusandra** [comment]
Hey, this is a very old presentation. The latest kea state is here: https://kea.js.org/ 
The `controller.rb` system is here: https://github.com/keajs/kea-rails-loader and https://github.com/keajs/kea-on-rails and 

It's basically a webpack plugin that reads "def method_name" lines from the controller.rb file and a ruby counterpart that lets you run public methods on controllers without going through the routes.rb file.
